
UPDATE `client` SET `open_data_id`= 80012 WHERE `name`='АДА';
UPDATE `client` SET `open_data_id`= 70017 WHERE `name`='АЛЕКСАНДРОВАЦ';
UPDATE `client` SET `open_data_id`= 70025 WHERE `name`='АЛЕКСИНАЦ';
UPDATE `client` SET `open_data_id`= 80039 WHERE `name`='АЛИБУНАР';
UPDATE `client` SET `open_data_id`= 80047 WHERE `name`='АПАТИН';
UPDATE `client` SET `open_data_id`= 70033 WHERE `name`='АРАНЂЕЛОВАЦ';
UPDATE `client` SET `open_data_id`= 70041 WHERE `name`='АРИЉЕ';
UPDATE `client` SET `open_data_id`= 70050 WHERE `name`='БАБУШНИЦА';
UPDATE `client` SET `open_data_id`= 70068 WHERE `name`='БАЈИНА БАШТА';
UPDATE `client` SET `open_data_id`= 70092 WHERE `name`='БАРАЈЕВО';
UPDATE `client` SET `open_data_id`= 70076 WHERE `name`='БАТОЧИНА';
UPDATE `client` SET `open_data_id`= 80055 WHERE `name`='БАЧ';
UPDATE `client` SET `open_data_id`= 80063 WHERE `name`='БАЧКА ПАЛАНКА';
UPDATE `client` SET `open_data_id`= 80071 WHERE `name`='БАЧКА ТОПОЛА';
UPDATE `client` SET `open_data_id`= 80080 WHERE `name`='БАЧКИ ПЕТРОВАЦ';
UPDATE `client` SET `open_data_id`= 70084 WHERE `name`='БЕЛА ПАЛАНКА';
UPDATE `client` SET `open_data_id`= 80098 WHERE `name`='БЕЛА ЦРКВА';
UPDATE `client` SET `open_data_id`= 80101 WHERE `name`='БЕОЧИН';
UPDATE `client` SET `open_data_id`= 80110 WHERE `name`='БЕЧЕЈ';
UPDATE `client` SET `open_data_id`= 70262 WHERE `name`='БЛАЦЕ';
UPDATE `client` SET `open_data_id`= 70289 WHERE `name`='БОГАТИЋ';
UPDATE `client` SET `open_data_id`= 70297 WHERE `name`='БОЈНИК';
UPDATE `client` SET `open_data_id`= 70319 WHERE `name`='БОЉЕВАЦ';
UPDATE `client` SET `open_data_id`= 70327 WHERE `name`='БОР';
UPDATE `client` SET `open_data_id`= 70335 WHERE `name`='БОСИЛЕГРАД';
UPDATE `client` SET `open_data_id`= 70343 WHERE `name`='БРУС';
UPDATE `client` SET `open_data_id`= 70351 WHERE `name`='БУЈАНОВАЦ';
UPDATE `client` SET `open_data_id`= 70360 WHERE `name`='ВАЉЕВО';
UPDATE `client` SET `open_data_id`= 70378 WHERE `name`='ВАРВАРИН';
UPDATE `client` SET `open_data_id`= 70386 WHERE `name`='ВЕЛИКА ПЛАНА';
UPDATE `client` SET `open_data_id`= 70394 WHERE `name`='ВЕЛИКО ГРАДИШТЕ';
UPDATE `client` SET `open_data_id`= 90018 WHERE `name`='ВИТИНА';
UPDATE `client` SET `open_data_id`= 70408 WHERE `name`='ВЛАДИМИРЦИ';
UPDATE `client` SET `open_data_id`= 70416 WHERE `name`='ВЛАДИЧИН ХАН';
UPDATE `client` SET `open_data_id`= 70424 WHERE `name`='ВЛАСОТИНЦЕ';
UPDATE `client` SET `open_data_id`= 70106 WHERE `name`='ВОЖДОВАЦ';
UPDATE `client` SET `open_data_id`= 70432 WHERE `name`='ВРАЊЕ';
UPDATE `client` SET `open_data_id`= 71358 WHERE `name`='ВРАЊСКА БАЊА';
UPDATE `client` SET `open_data_id`= 70114 WHERE `name`='ВРАЧАР';
UPDATE `client` SET `open_data_id`= 80462 WHERE `name`='ВРБАС';
UPDATE `client` SET `open_data_id`= 70459 WHERE `name`='ВРЊАЧКА БАЊА';
UPDATE `client` SET `open_data_id`= 80128 WHERE `name`='ВРШАЦ';
UPDATE `client` SET `open_data_id`= 90026 WHERE `name`='ВУЧИТРН';
UPDATE `client` SET `open_data_id`= 70467 WHERE `name`='ГАЏИН ХАН';
UPDATE `client` SET `open_data_id`= 90034 WHERE `name`='ГЛОГОВАЦ';
UPDATE `client` SET `open_data_id`= 90042 WHERE `name`='ГЊИЛАНЕ';
UPDATE `client` SET `open_data_id`= 70475 WHERE `name`='ГОЛУБАЦ';
UPDATE `client` SET `open_data_id`= 90336 WHERE `name`='ГОРА';
UPDATE `client` SET `open_data_id`= 70483 WHERE `name`='ГОРЊИ МИЛАНОВАЦ';
UPDATE `client` SET `open_data_id`= 70122 WHERE `name`='ГРОЦКА';
UPDATE `client` SET `open_data_id`= 70491 WHERE `name`='ДЕСПОТОВАЦ';
UPDATE `client` SET `open_data_id`= 90069 WHERE `name`='ДЕЧАНИ';
UPDATE `client` SET `open_data_id`= 70505 WHERE `name`='ДИМИТРОВГРАД';
UPDATE `client` SET `open_data_id`= 70513 WHERE `name`='ДОЉЕВАЦ';
UPDATE `client` SET `open_data_id`= 90085 WHERE `name`='ЂАКОВИЦА';
UPDATE `client` SET `open_data_id`= 80136 WHERE `name`='ЖАБАЉ';
UPDATE `client` SET `open_data_id`= 70521 WHERE `name`='ЖАБАРИ';
UPDATE `client` SET `open_data_id`= 70530 WHERE `name`='ЖАГУБИЦА';
UPDATE `client` SET `open_data_id`= 80144 WHERE `name`='ЖИТИШТЕ';
UPDATE `client` SET `open_data_id`= 70548 WHERE `name`='ЖИТОРАЂА';
UPDATE `client` SET `open_data_id`= 70556 WHERE `name`='ЗАЈЕЧАР';
UPDATE `client` SET `open_data_id`= 70149 WHERE `name`='ЗВЕЗДАРА';
UPDATE `client` SET `open_data_id`= 90352 WHERE `name`='ЗВЕЧАН';
UPDATE `client` SET `open_data_id`= 70157 WHERE `name`='ЗЕМУН';
UPDATE `client` SET `open_data_id`= 80152 WHERE `name`='ЗРЕЊАНИН';
UPDATE `client` SET `open_data_id`= 90093 WHERE `name`='ЗУБИН ПОТОК';
UPDATE `client` SET `open_data_id`= 70564 WHERE `name`='ИВАЊИЦА';
UPDATE `client` SET `open_data_id`= 80179 WHERE `name`='ИНЂИЈА';
UPDATE `client` SET `open_data_id`= 80187 WHERE `name`='ИРИГ';
UPDATE `client` SET `open_data_id`= 90107 WHERE `name`='ИСТОК';
UPDATE `client` SET `open_data_id`= 71048 WHERE `name`='ЈАГОДИНА';
UPDATE `client` SET `open_data_id`= 80195 WHERE `name`='КАЊИЖА';
UPDATE `client` SET `open_data_id`= 90115 WHERE `name`='КАЧАНИК';
UPDATE `client` SET `open_data_id`= 80209 WHERE `name`='КИКИНДА';
UPDATE `client` SET `open_data_id`= 70572 WHERE `name`='КЛАДОВО';
UPDATE `client` SET `open_data_id`= 90123 WHERE `name`='КЛИНА';
UPDATE `client` SET `open_data_id`= 70599 WHERE `name`='КНИЋ';
UPDATE `client` SET `open_data_id`= 70602 WHERE `name`='КЊАЖЕВАЦ';
UPDATE `client` SET `open_data_id`= 80217 WHERE `name`='КОВАЧИЦА';
UPDATE `client` SET `open_data_id`= 80225 WHERE `name`='КОВИН';
UPDATE `client` SET `open_data_id`= 70629 WHERE `name`='КОСЈЕРИЋ';
UPDATE `client` SET `open_data_id`= 90131 WHERE `name`='КОСОВО ПОЉЕ';
UPDATE `client` SET `open_data_id`= 90140 WHERE `name`='КОСОВСКА КАМЕНИЦА';
UPDATE `client` SET `open_data_id`= 90298 WHERE `name`='КОСОВСКА МИТРОВИЦА';
UPDATE `client` SET `open_data_id`= 71340 WHERE `name`='КОСТОЛАЦ';
UPDATE `client` SET `open_data_id`= 70637 WHERE `name`='КОЦЕЉЕВА';
UPDATE `client` SET `open_data_id`= 70645 WHERE `name`='КРАГУЈЕВАЦ';
UPDATE `client` SET `open_data_id`= 70653 WHERE `name`='КРАЉЕВО';
UPDATE `client` SET `open_data_id`= 70661 WHERE `name`='КРУПАЊ';
UPDATE `client` SET `open_data_id`= 70670 WHERE `name`='КРУШЕВАЦ';
UPDATE `client` SET `open_data_id`= 80233 WHERE `name`='КУЛА';
UPDATE `client` SET `open_data_id`= 70688 WHERE `name`='КУРШУМЛИЈА';
UPDATE `client` SET `open_data_id`= 70696 WHERE `name`='КУЧЕВО';
UPDATE `client` SET `open_data_id`= 70165 WHERE `name`='ЛАЗАРЕВАЦ';
UPDATE `client` SET `open_data_id`= 70700 WHERE `name`='ЛАЈКОВАЦ';
UPDATE `client` SET `open_data_id`= 71277 WHERE `name`='ЛАПОВО';
UPDATE `client` SET `open_data_id`= 70718 WHERE `name`='ЛЕБАНЕ';
UPDATE `client` SET `open_data_id`= 90158 WHERE `name`='ЛЕПОСАВИЋ';
UPDATE `client` SET `open_data_id`= 70726 WHERE `name`='ЛЕСКОВАЦ';
UPDATE `client` SET `open_data_id`= 90166 WHERE `name`='ЛИПЉАН';
UPDATE `client` SET `open_data_id`= 70734 WHERE `name`='ЛОЗНИЦА';
UPDATE `client` SET `open_data_id`= 70742 WHERE `name`='ЛУЧАНИ';
UPDATE `client` SET `open_data_id`= 70769 WHERE `name`='ЉИГ';
UPDATE `client` SET `open_data_id`= 70777 WHERE `name`='ЉУБОВИЈА';
UPDATE `client` SET `open_data_id`= 70785 WHERE `name`='МАЈДАНПЕК';
UPDATE `client` SET `open_data_id`= 70793 WHERE `name`='МАЛИ ЗВОРНИК';
UPDATE `client` SET `open_data_id`= 80241 WHERE `name`='МАЛИ ИЂОШ';
UPDATE `client` SET `open_data_id`= 70807 WHERE `name`='МАЛО ЦРНИЋЕ';
UPDATE `client` SET `open_data_id`= 70815 WHERE `name`='МЕДВЕЂА';
UPDATE `client` SET `open_data_id`= 71331 WHERE `name`='МЕДИЈАНА';
UPDATE `client` SET `open_data_id`= 70823 WHERE `name`='МЕРОШИНА';
UPDATE `client` SET `open_data_id`= 70831 WHERE `name`='МИОНИЦА';
UPDATE `client` SET `open_data_id`= 70173 WHERE `name`='МЛАДЕНОВАЦ';
UPDATE `client` SET `open_data_id`= 70840 WHERE `name`='НЕГОТИН';
UPDATE `client` SET `open_data_id`= 71285 WHERE `name`='НИШКА БАЊА';
UPDATE `client` SET `open_data_id`= 70866 WHERE `name`='НОВА ВАРОШ';
UPDATE `client` SET `open_data_id`= 80250 WHERE `name`='НОВА ЦРЊА';
UPDATE `client` SET `open_data_id`= 70181 WHERE `name`='НОВИ БЕОГРАД';
UPDATE `client` SET `open_data_id`= 80268 WHERE `name`='НОВИ БЕЧЕЈ';
UPDATE `client` SET `open_data_id`= 80276 WHERE `name`='НОВИ КНЕЖЕВАЦ';
UPDATE `client` SET `open_data_id`= 70874 WHERE `name`='НОВИ ПАЗАР';
UPDATE `client` SET `open_data_id`= 89010 WHERE `name`='НОВИ САД';
UPDATE `client` SET `open_data_id`= 90182 WHERE `name`='НОВО БРДО';
UPDATE `client` SET `open_data_id`= 90204 WHERE `name`='ОБИЛИЋ';
UPDATE `client` SET `open_data_id`= 70190 WHERE `name`='ОБРЕНОВАЦ';
UPDATE `client` SET `open_data_id`= 80292 WHERE `name`='ОПОВО';
UPDATE `client` SET `open_data_id`= 90212 WHERE `name`='ОРАХОВАЦ';
UPDATE `client` SET `open_data_id`= 70882 WHERE `name`='ОСЕЧИНА';
UPDATE `client` SET `open_data_id`= 80306 WHERE `name`='ОЏАЦИ';
UPDATE `client` SET `open_data_id`= 70203 WHERE `name`='ПАЛИЛУЛА (БЕОГРАД)';
UPDATE `client` SET `open_data_id`= 71323 WHERE `name`='ПАЛИЛУЛА (НИШ)';
UPDATE `client` SET `open_data_id`= 71307 WHERE `name`='ПАНТЕЛЕЈ';
UPDATE `client` SET `open_data_id`= 80314 WHERE `name`='ПАНЧЕВО';
UPDATE `client` SET `open_data_id`= 70904 WHERE `name`='ПАРАЋИН';
UPDATE `client` SET `open_data_id`= 70912 WHERE `name`='ПЕТРОВАЦ НА МЛАВИ';
UPDATE `client` SET `open_data_id`= 90239 WHERE `name`='ПЕЋ';
UPDATE `client` SET `open_data_id`= 80322 WHERE `name`='ПЕЋИНЦИ';
UPDATE `client` SET `open_data_id`= 70939 WHERE `name`='ПИРОТ';
UPDATE `client` SET `open_data_id`= 80349 WHERE `name`='ПЛАНДИШТЕ';
UPDATE `client` SET `open_data_id`= 90247 WHERE `name`='ПОДУЈЕВО';
UPDATE `client` SET `open_data_id`= 70947 WHERE `name`='ПОЖАРЕВАЦ';
UPDATE `client` SET `open_data_id`= 70955 WHERE `name`='ПОЖЕГА';
UPDATE `client` SET `open_data_id`= 70963 WHERE `name`='ПРЕШЕВО';
UPDATE `client` SET `open_data_id`= 70971 WHERE `name`='ПРИБОЈ';
UPDATE `client` SET `open_data_id`= 90255 WHERE `name`='ПРИЗРЕН';
UPDATE `client` SET `open_data_id`= 70980 WHERE `name`='ПРИЈЕПОЉЕ';
UPDATE `client` SET `open_data_id`= 90263 WHERE `name`='ПРИШТИНА';
UPDATE `client` SET `open_data_id`= 70998 WHERE `name`='ПРОКУПЉЕ';
UPDATE `client` SET `open_data_id`= 71005 WHERE `name`='РАЖАЊ';
UPDATE `client` SET `open_data_id`= 70211 WHERE `name`='РАКОВИЦА';
UPDATE `client` SET `open_data_id`= 71013 WHERE `name`='РАЧА';
UPDATE `client` SET `open_data_id`= 71021 WHERE `name`='РАШКА';
UPDATE `client` SET `open_data_id`= 71030 WHERE `name`='РЕКОВАЦ';
UPDATE `client` SET `open_data_id`= 80357 WHERE `name`='РУМА';
UPDATE `client` SET `open_data_id`= 70220 WHERE `name`='САВСКИ ВЕНАЦ';
UPDATE `client` SET `open_data_id`= 71056 WHERE `name`='СВИЛАЈНАЦ';
UPDATE `client` SET `open_data_id`= 71064 WHERE `name`='СВРЉИГ';
UPDATE `client` SET `open_data_id`= 71366 WHERE `name`='СЕВОЈНО';
UPDATE `client` SET `open_data_id`= 80365 WHERE `name`='СЕНТА';
UPDATE `client` SET `open_data_id`= 80373 WHERE `name`='СЕЧАЊ';
UPDATE `client` SET `open_data_id`= 71072 WHERE `name`='СЈЕНИЦА';
UPDATE `client` SET `open_data_id`= 71099 WHERE `name`='СМЕДЕРЕВО';
UPDATE `client` SET `open_data_id`= 71102 WHERE `name`='СМЕДЕРЕВСКА ПАЛАНКА';
UPDATE `client` SET `open_data_id`= 71129 WHERE `name`='СОКОБАЊА';
UPDATE `client` SET `open_data_id`= 80381 WHERE `name`='СОМБОР';
UPDATE `client` SET `open_data_id`= 70238 WHERE `name`='СОПОТ';
UPDATE `client` SET `open_data_id`= 90271 WHERE `name`='СРБИЦА';
UPDATE `client` SET `open_data_id`= 80390 WHERE `name`='СРБОБРАН';
UPDATE `client` SET `open_data_id`= 80403 WHERE `name`='СРЕМСКА МИТРОВИЦА';
UPDATE `client` SET `open_data_id`= 80411 WHERE `name`='СРЕМСКИ КАРЛОВЦИ';
UPDATE `client` SET `open_data_id`= 80420 WHERE `name`='СТАРА ПАЗОВА';
UPDATE `client` SET `open_data_id`= 70246 WHERE `name`='СТАРИ ГРАД';
UPDATE `client` SET `open_data_id`= 80438 WHERE `name`='СУБОТИЦА';
UPDATE `client` SET `open_data_id`= 90280 WHERE `name`='СУВА РЕКА';
UPDATE `client` SET `open_data_id`= 71137 WHERE `name`='СУРДУЛИЦА';
UPDATE `client` SET `open_data_id`= 71293 WHERE `name`='СУРЧИН';
UPDATE `client` SET `open_data_id`= 80446 WHERE `name`='ТЕМЕРИН';
UPDATE `client` SET `open_data_id`= 80454 WHERE `name`='ТИТЕЛ';
UPDATE `client` SET `open_data_id`= 71153 WHERE `name`='ТОПОЛА';
UPDATE `client` SET `open_data_id`= 71161 WHERE `name`='ТРГОВИШТЕ';
UPDATE `client` SET `open_data_id`= 71170 WHERE `name`='ТРСТЕНИК';
UPDATE `client` SET `open_data_id`= 71188 WHERE `name`='ТУТИН';
UPDATE `client` SET `open_data_id`= 71196 WHERE `name`='ЋИЋЕВАЦ';
UPDATE `client` SET `open_data_id`= 71200 WHERE `name`='ЋУПРИЈА';
UPDATE `client` SET `open_data_id`= 71218 WHERE `name`='УБ';
UPDATE `client` SET `open_data_id`= 71145 WHERE `name`='УЖИЦЕ';
UPDATE `client` SET `open_data_id`= 90301 WHERE `name`='УРОШЕВАЦ';
UPDATE `client` SET `open_data_id`= 71315 WHERE `name`='ЦРВЕНИ КРСТ';
UPDATE `client` SET `open_data_id`= 71226 WHERE `name`='ЦРНА ТРАВА';
UPDATE `client` SET `open_data_id`= 71234 WHERE `name`='ЧАЈЕТИНА';
UPDATE `client` SET `open_data_id`= 71242 WHERE `name`='ЧАЧАК';
UPDATE `client` SET `open_data_id`= 80489 WHERE `name`='ЧОКА';
UPDATE `client` SET `open_data_id`= 70254 WHERE `name`='ЧУКАРИЦА';
UPDATE `client` SET `open_data_id`= 71269 WHERE `name`='ШАБАЦ';
UPDATE `client` SET `open_data_id`= 80497 WHERE `name`='ШИД';
UPDATE `client` SET `open_data_id`= 90310 WHERE `name`='ШТИМЉЕ';
UPDATE `client` SET `open_data_id`= 90328 WHERE `name`='ШТРПЦЕ';
